### ISSUE TITLE
Support installation via DaemonSet in Kubernetes clusters

### ISSUE THREAD

**Issue by tamalsaha** [rexray/rexray#1116]
Is it possible to install `rexray` using DaemonSet in a Kubernetes cluster? This will make deploying this to a running cluster much easier.

**Comment by clintkitson** [comment]
So far this hasn't been relevant because RR has only been relevant to K8s
through the flex interface. This interface endppoint could not be
containerized, so no it wasn't investigated.  With introduction of CSI this
is not the case and there will be some new methods to launch a CSI plugin
which make this easier.

**Comment by AceHack** [comment]
Any update on this?

**Comment by AceHack** [comment]
Also if you look at rook.io they support a touchless install via a helm chart that works with flex plugin model.  You don't have to do any manual work to the nodes first, just pure K8s install only.  Seems like you could do something like that.

https://rook.io/docs/rook/master/helm-operator.html


https://rook.io/docs/rook/master/helm-operator.html

**Comment by akutz** [comment]
Cool!
