### ISSUE TITLE
Seeking advice for contribution

### ISSUE THREAD

**Issue by tamalsaha** [rexray/rexray#1117]
We develop a Kubernetes installer https://github.com/appscode/pharmer . We would like see support for additional cloud providers namely Linode and Vultr. Do you accept external contribution? What is the general process involved in adding support for additional cloud providers?

**Comment by kacole2** [comment]
@tamalsaha thanks for asking about contributions. We certainly accept external contributions. 

Let me give you a brief history and tell you about what's coming next so you have an idea of where to start. REX-Ray was built on top of a library called [libStorage](https://github.com/thecodeteam/libstorage) that has all of the current storage and cloud providers baked into it. A few months ago we made the decision to [merge libStorage](https://github.com/thecodeteam/rexray/pull/932) into REX-Ray for consistency and completeness.

The next big shift happening is the introduction of the [Container Storage Interface](https://github.com/container-storage-interface/) (CSI). REX-Ray is currently keeping parity with the 0.1 release that is happening at KubeCon. In addition, CSI will be a new alpha feature in Kubernetes 1.9. To begin the adoption of this new interface, REX-Ray can accept incoming CSI requests and even has a [southbound bridge for use with Docker](https://github.com/thecodeteam/rexray/pull/1055). 

Very soon we will begin the process of taking our existing libStorage drivers and porting them over to CSI Drivers that can still be packaged up and used by REX-Ray. With that said, there are plenty of things that a generic CSI driver lacks vs the features built-in to REX-Ray so that's why we are packaging them. Our advice to you is to write the Linode and Vultr drivers as CSI Drivers. Check out our [csi-nfs](https://github.com/thecodeteam/csi-nfs), [csi-vfs](https://github.com/thecodeteam/csi-vfs), and [csi-blockdevice](https://github.com/thecodeteam/csi-blockdevices) drivers as a place to start. Please note that these are not up to date with the current 0.1 spec but will be updated very soon. The team is currently busy creating 2 new CSI drivers that we will launch at KubeCon. Once you have a Linode and Vultr CSI driver, a PR can be submitted for inclusion with REX-Ray and they can be used with Kubernetes CSI, Kubernetes Flex, and Docker with the southbound bridge for Docker Swarm and Mesos. Mesos is working on their CSI implementation which is scheduled for a future release.

Hope that helps!

**Comment by tamalsaha** [comment]
Thanks for the detailed answer @kacole2 . Sorry for not responding sooner.

>  there are plenty of things that a generic CSI driver lacks vs the features built-in to REX-Ray so that's why we are packaging them.

What features are you referring to? I understand that RexRay makes CSI drivers work with other scenarios. We are singularly interested in Kubernetes, at least for now. What things will be missing if we implement the drivers like csi-*** ?

**Comment by clintkitson** [comment]
@tamalsaha The driver itself can serve a CSI endpoint. In the short term the relevance is dependent on the depth of implementations by COs. For example, K8s 1.9 will support CSI but only in basic functionality for orchestrating volumes, and not for provisioning volumes. 

REX-Ray will provide an interoperability layer for the CSI drivers. So develop the CSI driver, and then let REX-Ray expose that driver in numerous ways including CSI, Docker, Flex, etc.

**Comment by vielmetti** [comment]
Interested also in seeing Packet as a storage provider.

**Comment by clintkitson** [comment]
We are as well @vielmetti. I suggest checking out the [gocsi](https://github.com/thecodeteam/gocsi) repo for a starting point! The [csi-vfs](https://github.com/thecodeteam/csi-vfs) driver should be a good starting point.

The following command will create a stub CSI driver to begin development from.
`docker run -it golang:1.8.3 bash -c "go get github.com/thecodeteam/gocsi && make -C src/github.com/thecodeteam/gocsi csi-sp"`

**Comment by basz** [comment]
subscribing because of interest in a linode plugin for block storage

**Comment by kevb** [comment]
I'd love to see a linode & vultr plugin. Happy to contribute to a bounty on this if someone wants to build it. Watching.

**Comment by displague** [comment]
Linode volume drivers for CSI and Docker exist now:

* https://github.com/linode/linode-blockstorage-csi-driver/
* https://github.com/linode/docker-volume-linode

What's the process and benefit of adding them to RexRay?  Are there particular clients that are already aware of the RexRay bridge, such that using Linode mounts in those environments would just be a text/configuration change?
